import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { supabase } from "../utils/supabaseClient";

export default function Home() {
  const router = useRouter();
  const [imageNum, setImageNum] = useState(0);
  useEffect(() => {
    const getInitData = async () => {
      const initData = await supabase.from("image-num").select("*").eq("id", 2);
      console.log(initData);
      setImageNum(initData.data[0].image_num);
    };

    getInitData();

    const imageNumData = supabase.from("image-num").on("UPDATE", (payload) => {
      console.log(payload.new);
      if (payload.new.id === 2) {
        setImageNum(payload.new.image_num);
      }
      if (payload.new.id === 4) {
        if (payload.new.image_num === 69) {
          router.reload(window.location.pathname);
        }
      }
    });

    imageNumData.subscribe();

    return;
  }, []);

  return (
    <div>
      <Head>
        <title>Seth GCX Overlay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Image
          src={`/StJudesProgress_Extended_${imageNum}.jpg`}
          width="981"
          height="519"
        />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  return {
    props: {
      imageNum: 0,
    }, // will be passed to the page component as props
  };
}
